### ISSUE TITLE
Add ability to create user dictionary

### ISSUE THREAD

**Issue by siddbudd** [transcrobes/transcrobes#24]
Users should be able to add their private glossaries. You mentioned in "Getting started" that you like reading sci-fi and tech news. I do too, and those areas seem to be covered by the (presumably open-source) dictionary sources you are using. However, in addition, I like reading Buddhist texts way above my level, and open dictionaries general do not cover this specific vocabulary. Therefore, it would be very useful if I could add my own glossary, e.g. in a Pleco style format (hanzi {tab} pinyin {tab} definition). Please consider adding such functionality.

Update: Words in the user's glossary should be shown above existing main entries. E.g. just found the word "根器" as "Root device", it has a totally different meaning in Buddhism (capacities, faculties, abilities, roots).

**Comment by AntonOfTheWoods** [comment]
Thanks for the suggestion @siddbudd . This has definitely been floating round as an idea since the beginning. Actually the "lightbulb" that set me on the path to developing this was that I had *all* my Chinese vocab knowledge in Anki, and what I wanted was help with everything that wasn't already in there...

So today there are already partial structures for doing this but they aren't super well-adapted. The cards that you have in repetrobes have free/manual "front" and "back" database entries, and these cards are also what determines whether you "know" a word or not (so the information is already loaded and could be shown). Today you can edit the front of the meaning card, though that only shows up (currently) in repetrobes and in notrobes (which original meant "Notes", a la Anki).

So I could make it easier to edit all of the "front"s, and then make those available in the popups. I am a little less inclined to want to let users set what happens in the glosses because deciding what goes in there is already reasonably complicated (it takes part of speech and lenth of gloss into account), at least for the English (L1) definition, and I would like to get some proper intelligence (using word alignment from sentence translations, etc) at some point.

So what do you think? Should I make all the fronts and back overridable? Then if there is something there, I could put that in the popup. Or something else?

**Comment by AntonOfTheWoods** [comment]
@siddbudd I have updated production with a a version that works.

I have NOT yet properly documented it and have noticed a couple of little bugs but the main functionality is there. Basically, you can import a dictionary and that dictionary can be prioritised in most places (so in repetrobes, the content interfaces, etc.). 

For the content interfaces the system tries to use as much information as possible for determining the correct gloss. That means that if you don't put a part of speech, it will prefer other entries that *do* have a part of speech. You might well not have the parts of speech, so there is also an option to force the first definition provider that has the word called "Strict Provider Ordering", which will only fall back to another provider if the word doesn't appear in the highest priority dictionary at all.

Please let me know what you think! (I have also added quite a bit of extra stuff around radicals, component ordering etc.)

Should be fixed by https://github.com/transcrobes/transcrobes/commit/25830bf2719b5072bf7b7392e17f75e703d2479c

I will close this as the feature is there now, please create bug reports if you find any or there are extra features you need!
